### ISSUE TITLE
5 items in array, Angulargid ng-repeat displays only 4

### ISSUE THREAD

**Issue by alereisan** [s-yadav/angulargrid#41] opened 2016-02-29 19:37 UTC
My angulargrid setup always misses 1 item.

For example if I have 5 items in the "shots" array angulargrid displays only 4. But when I do {{shots.length}} outside of the angulargrid div, I get 5, so they are deffinitely all there. I am using angulargrid on multiple sub-pages - its everywhere the same, always 1 item missing.

I am using the ag-infinite-scroll functionality, and I load in the first page by resolve function of ui-router.
Second page upwards gets loaded by `ag-infinite-scroll="vm.loadMoreShots()"`

EDIT: This happens only with `ag-performant-scroll="true"`

**Comment by ThrowableFactory** [comment] 2016-03-16 01:22
I've found this problem , too .
I think it may caused by slice here .
slice(0,3) returns object indexed 0 to 2 , not 0 to 3 , so one element will get lost if performant scroll enabled.
With to value+1 given , problem solved.

![ecas2](https://cloud.githubusercontent.com/assets/13232736/13799252/9a1b3896-eb58-11e5-8ad6-07abe0cff25a.PNG)

**Comment by s-yadav** [comment] 2016-03-16 18:47
Thanks @ThrowableFactory , You got it.  I merged your pull request.

**Closed** 2016-03-20 16:39 UTC
