### ISSUE TITLE
Elements get squished on window resize

### ISSUE THREAD

**Issue by vasilak** [s-yadav/angulargrid#44] opened 2016-03-17 18:21 UTC
Hi there.

First of all, great plugin, thanks a lot!
There seems to be a small issue when the window gets resized. The images in the grid get squished.
I have noticed this happens when opening the javascript console in the browser and then resizing the window.

So to replicate the issue:
1) Load the page with the images
2) Open the JS console so that the content window gets smaller
3) With the JS console still open try to resize the browser window

**Comment by s-yadav** [comment] 2016-09-21 15:05
Not able to reproduce. Closing it.

**Closed by s-yadav** 2016-09-21 15:05 UTC
